### ISSUE TITLE
Elaboration requested on the config's 'data_files' 

### ISSUE THREAD

**Issue by MarkTension** [edward1997104/Wavelet-Generation#2]
Thanks for your interesting work!  I have a question on the config file.
What is the exact difference in config settings when generating the 2 different data files? I assumed simply reducing resolution_index in convert_wavelet.py by 1 would generate the second wavelet file from the SDFs, but is that correct?

`data_files = [('wavelet_data/03001627_0.1_bior6.8_3_zero.npy', 3), ('wavelet_data/03001627_0.1_bior6.8_2_zero.npy', 2)]`

Thanks a lot!

**Comment by edward1997104** [comment]
Yes, you are correct. If you reduce the resolution_index by 1, you can generate the second file, which is the detail coefficient volume for the shape. Generally, the resolution_index of "3" represents the coarse coefficient volume, while "2" represents the detail coefficient volume.
